export const LOAD_ALL_GITHUB_USER = "LOAD_ALL_GITHUB_USER";
export const LOAD_ALL_REPO_OF_A_USER = "LOAD_ALL_REPO_OF_A_USER";
export const SELECTED_REPOSITORY_USER = "SELECTED_REPOSITORY_USER";
export const SEARCH_USER = "SEARCH_USER";
export const SELECTED_USER = "SELECTED_USER";
export const GITHUB_USER_MEDIUM_INFORMATION =
  "GITHUB_USER_MEDIUM_INFORMATION";
